# Generated by Django 5.2.6 on 2025-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('engine_cc', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('kilometers_driven', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='buy_bikes/')),
                ('booked', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
