# Generated by Django 5.2.6 on 2025-09-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikelisting',
            name='category',
            field=models.CharField(choices=[('scooty', 'Scooty'), ('motorbike', 'Motor Bike'), ('ev', 'EV')], default='motorbike', max_length=20),
        ),
    ]
