# Generated by Django 5.2.6 on 2025-09-15 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_bikelisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikelisting',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='rc_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='refurbished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='registration_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='rto_city',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='rto_state',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bike_gallery/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='buy.bikelisting')),
            ],
        ),
    ]
