# Generated by Django 5.2.6 on 2025-09-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_bikelisting_finance_bikelisting_insurance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='booking_steps/')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
