# Generated by Django 5.2.6 on 2025-09-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_bookingstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikelisting',
            name='abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='front_brake_type',
            field=models.CharField(default='Drum', max_length=50),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='ignition_type',
            field=models.CharField(default='Kick & Self Start', max_length=100),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='odometer_type',
            field=models.CharField(default='Analogue', max_length=50),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='rear_brake_type',
            field=models.CharField(default='Drum', max_length=50),
        ),
        migrations.AddField(
            model_name='bikelisting',
            name='wheel_type',
            field=models.CharField(default='Steel', max_length=50),
        ),
    ]
