# Generated by Django 5.2.6 on 2025-09-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_bike',
            field=models.ImageField(blank=True, null=True, upload_to='footer_bikes/'),
        ),
    ]
