# Generated by Django 5.2.6 on 2025-09-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_footer_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_logos/'),
        ),
    ]
