# Generated by Django 5.2.6 on 2025-09-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_footer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='login/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
