# Generated by Django 5.2.6 on 2025-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bikecarouselimage_homecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rider/')),
                ('content', models.TextField()),
                ('button_text', models.CharField(default='Read More', max_length=100)),
                ('button_link', models.URLField(default='#')),
            ],
        ),
    ]
