# Generated by Django 5.2.6 on 2025-09-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ridersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='support_features/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='button_link',
            field=models.URLField(default='buy_bike'),
        ),
        migrations.AlterField(
            model_name='ridersection',
            name='button_link',
            field=models.CharField(default='about_us', max_length=255),
        ),
    ]
