# Generated by Django 5.2.6 on 2025-09-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(help_text='Image for the About Us section (left side)', upload_to='about/')),
                ('mission_image', models.ImageField(help_text='Image for the Mission section background', upload_to='about/')),
            ],
        ),
    ]
