# Generated by Django 5.2.6 on 2025-09-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='approach/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls image order (0 = top left)')),
            ],
        ),
    ]
