# Generated by Django 5.2.6 on 2025-09-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_approachsectionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedRidersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Trusted by Riders Like You', max_length=200)),
                ('description', models.TextField(default='From smooth sales to great secondhand finds...')),
                ('image', models.ImageField(upload_to='trusted_riders/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
