# Generated by Django 5.2.6 on 2025-09-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reason', models.CharField(choices=[('General Enquiry', 'General Enquiry'), ('Buy a Bike', 'Buy a Bike'), ('Sell a Bike', 'Sell a Bike'), ('Exchange a Bike', 'Exchange a Bike'), ('RTO Service', 'RTO Service'), ('Others', 'Others')], max_length=50)),
                ('source', models.CharField(choices=[('OLX', 'OLX'), ('Instagram', 'Instagram'), ('Youtube', 'Youtube'), ('Google', 'Google'), ('Website', 'Website'), ('Facebook', 'Facebook'), ('Walk-in', 'Walk-in')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
