# Generated by Django 5.2.6 on 2025-09-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_howitworksstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('image', models.ImageField(upload_to='sell_hero/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
